-- PostgreSQL / Supabase Schema and Seed Data

-- -------------------------------------------------------------
-- SCHEMA CREATION
-- -------------------------------------------------------------

CREATE TABLE regions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    iso3 VARCHAR(3) NOT NULL UNIQUE CHECK (length(iso3) = 3),
    region_id BIGINT NOT NULL REFERENCES regions(id) ON DELETE RESTRICT,
    surface_area_sq_km_2023 NUMERIC
);

CREATE TABLE gdp (
    country_id BIGINT NOT NULL REFERENCES countries(id) ON DELETE CASCADE,
    year INTEGER NOT NULL,
    gdp_usd_billion NUMERIC NOT NULL CHECK (gdp_usd_billion >= 0),
    PRIMARY KEY (country_id, year)
);

CREATE TABLE population (
    country_id BIGINT NOT NULL REFERENCES countries(id) ON DELETE CASCADE,
    year INTEGER NOT NULL,
    population BIGINT NOT NULL CHECK (population >= 0),
    PRIMARY KEY (country_id, year)
);

CREATE TABLE exports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE country_exports (
    country_id BIGINT NOT NULL REFERENCES countries(id) ON DELETE CASCADE,
    export_id BIGINT NOT NULL REFERENCES exports(id) ON DELETE CASCADE,
    PRIMARY KEY (country_id, export_id)
);

CREATE TABLE industries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE country_industries (
    country_id BIGINT NOT NULL REFERENCES countries(id) ON DELETE CASCADE,
    industry_id BIGINT NOT NULL REFERENCES industries(id) ON DELETE CASCADE,
    PRIMARY KEY (country_id, industry_id)
);

-- Indexing foreign keys for query performance
CREATE INDEX idx_countries_region ON countries(region_id);
CREATE INDEX idx_gdp_country ON gdp(country_id);
CREATE INDEX idx_population_country ON population(country_id);
CREATE INDEX idx_country_exports_export ON country_exports(export_id);
CREATE INDEX idx_country_industries_industry ON country_industries(industry_id);

-- -------------------------------------------------------------
-- ROW LEVEL SECURITY (SUPABASE SPECIFIC)
-- -------------------------------------------------------------

ALTER TABLE regions ENABLE ROW LEVEL SECURITY;
ALTER TABLE countries ENABLE ROW LEVEL SECURITY;
ALTER TABLE gdp ENABLE ROW LEVEL SECURITY;
ALTER TABLE population ENABLE ROW LEVEL SECURITY;
ALTER TABLE exports ENABLE ROW LEVEL SECURITY;
ALTER TABLE country_exports ENABLE ROW LEVEL SECURITY;
ALTER TABLE industries ENABLE ROW LEVEL SECURITY;
ALTER TABLE country_industries ENABLE ROW LEVEL SECURITY;

-- Allow public read-only access for all tables
CREATE POLICY "Allow public read access" ON regions FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON countries FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON gdp FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON population FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON exports FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON country_exports FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON industries FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON country_industries FOR SELECT USING (true);

-- -------------------------------------------------------------
-- SAMPLE DATA INSERTION
-- -------------------------------------------------------------

INSERT INTO regions (id, name) VALUES
(1, 'North America'),
(2, 'Europe'),
(3, 'East Asia');

INSERT INTO countries (id, name, iso3, region_id, surface_area_sq_km_2023) VALUES
(1, 'United States', 'USA', 1, 9833517.0),
(2, 'Germany', 'DEU', 2, 357022.0),
(3, 'Japan', 'JPN', 3, 377975.0);

INSERT INTO gdp (country_id, year, gdp_usd_billion) VALUES
(1, 2022, 25462.7),
(1, 2023, 27360.9),
(2, 2022, 4072.2),
(2, 2023, 4456.1),
(3, 2022, 4231.1),
(3, 2023, 4212.9);

INSERT INTO population (country_id, year, population) VALUES
(1, 2022, 333287557),
(1, 2023, 334914895),
(2, 2022, 83797985),
(2, 2023, 84358845),
(3, 2022, 125124000),
(3, 2023, 124516700);

INSERT INTO exports (id, name) VALUES
(1, 'Refined Petroleum'),
(2, 'Automobiles'),
(3, 'Integrated Circuits'),
(4, 'Pharmaceuticals');

INSERT INTO country_exports (country_id, export_id) VALUES
(1, 1),
(1, 3),
(2, 2),
(2, 4),
(3, 2),
(3, 3);

INSERT INTO industries (id, name) VALUES
(1, 'Aerospace'),
(2, 'Automotive'),
(3, 'Consumer Electronics'),
(4, 'Chemicals');

INSERT INTO country_industries (country_id, industry_id) VALUES
(1, 1),
(1, 3),
(2, 2),
(2, 4),
(3, 2),
(3, 3);

-- Sync identity sequences so future auto-generated IDs start after the max explicit ID
SELECT setval(pg_get_serial_sequence('regions', 'id'), (SELECT MAX(id) FROM regions));
SELECT setval(pg_get_serial_sequence('countries', 'id'), (SELECT MAX(id) FROM countries));
SELECT setval(pg_get_serial_sequence('exports', 'id'), (SELECT MAX(id) FROM exports));
SELECT setval(pg_get_serial_sequence('industries', 'id'), (SELECT MAX(id) FROM industries));